org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

reactNativeArchitectures=arm64-v8a,armeabi-v7a

newArchEnabled=true

hermesEnabled=true

expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

android.enableProguardInReleaseBuilds=true
android.enableShrinkResourcesInReleaseBuilds=true

expo.useLegacyPackaging=true

EX_DEV_CLIENT_NETWORK_INSPECTOR=false
